// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteadySchedule.Data;

#nullable disable

namespace SteadySchedule.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408153749_AddPositions")]
    partial class AddPositions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SteadySchedule.Data.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("WeekStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("SteadySchedule.Domain.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ApprovedOvertime")
                        .HasColumnType("bit");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ShiftId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("SteadySchedule.Domain.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FridayAnyTime")
                        .HasColumnType("bit");

                    b.Property<bool>("FridayAvailable")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("FridayEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("FridayStart")
                        .HasColumnType("time");

                    b.Property<int>("MaxHoursPerWeek")
                        .HasColumnType("int");

                    b.Property<bool>("MondayAnyTime")
                        .HasColumnType("bit");

                    b.Property<bool>("MondayAvailable")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("MondayEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("MondayStart")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionsQualified")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SaturdayAnyTime")
                        .HasColumnType("bit");

                    b.Property<bool>("SaturdayAvailable")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("SaturdayEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("SaturdayStart")
                        .HasColumnType("time");

                    b.Property<bool>("SundayAnyTime")
                        .HasColumnType("bit");

                    b.Property<bool>("SundayAvailable")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("SundayEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("SundayStart")
                        .HasColumnType("time");

                    b.Property<bool>("ThursdayAnyTime")
                        .HasColumnType("bit");

                    b.Property<bool>("ThursdayAvailable")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("ThursdayEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("ThursdayStart")
                        .HasColumnType("time");

                    b.Property<bool>("TuesdayAnyTime")
                        .HasColumnType("bit");

                    b.Property<bool>("TuesdayAvailable")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("TuesdayEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("TuesdayStart")
                        .HasColumnType("time");

                    b.Property<bool>("WednesdayAnyTime")
                        .HasColumnType("bit");

                    b.Property<bool>("WednesdayAvailable")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("WednesdayEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("WednesdayStart")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SteadySchedule.Domain.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("SteadySchedule.Domain.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlotGroupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("SteadySchedule.Domain.Assignment", b =>
                {
                    b.HasOne("SteadySchedule.Domain.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SteadySchedule.Domain.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Shift");
                });
#pragma warning restore 612, 618
        }
    }
}
